drop table time_entry if exists
create table time_entry (time_entry_id bigint generated by default as identity, account_name varchar(255) not null, date date not null, fe_name varchar(255) not null, hours float not null, primary key (time_entry_id))
	