---
platform: linux

image_resource:
  type: docker-image
  source: {repository: jigsheth57/pcfworkshop}

inputs:
  - name: lab-repo
  - name: lab-release

run:
  path: lab-repo/ci/tasks/cf-deployment.sh

params:
  API_ENDPOINT: {{cf-dev-api}}
  USERNAME: {{cf-dev-username}}
  PASSWORD: {{cf-dev-password}}
  ORG: {{cf-dev-organization}}
  SPACE: {{cf-dev-space}}
  CF_APPS_DOMAIN: {{cf-dev-domain}}
  CF_APP_NAME: timetracking
