apiVersion: kpack.io/v1alpha1
kind: Image
metadata:
  name: fetimetracking
  namespace: default
spec:
  builder:
    kind: ClusterBuilder
    name: default
  serviceAccount: default
  source:
    git:
      revision: v1.2
      url: https://github.com/jigsheth57/fe-time-tracking
  tag: kind-registry:5000/fetimetracking
